# Makefile for EF demo binary

EF_TOCK_BASEDIR := ../../../encapfn-tock
EF_BIN_NAME     := efdemo
EF_TARGET       := rv32imac

SRCDIR          := ./c_src/

include $(EF_TOCK_BASEDIR)/encapfn_c_rt/EncapfnTBF.mk
